#!/bin/bash

calc()
{
case "$1" in
"sum")
echo "$(($2 + $3))"
;;

"sub")
echo "$(($2 - $3))"
;;

"mul")
echo "$(($2 * $3))"
;;

"div")
if (("$3" == "0"))
then echo "Div on zero!!!"
else
echo "$(($2 / $3))"
fi
;;

esac
}
