#!/bin/bash
source number

calc()
{
if ! (number $2)
then echo "First argument not number!" 1>&2
return 1
fi
#comment
if ! (number $3)
then echo "Second argument not number!" 1>&2
return 1
fi

case "$1" in
"sum")
echo "$(($2 + $3))"
;;

"sub")
echo "$(($2 - $3))"
;;

"mul")
echo "$(($2 * $3))"
;;

"div")
if (("$3" == "0"))
then echo "Div on zero!!!" 1>&2
else
echo "$(($2 / $3))"
fi
;;

*)
"I don't know $1 command" 1>&2
esac
}

